name: nrf_ble_dfu
description: "The Nordic DFU over BLE library helps enable firmware updates of BLE devices over Bluetooth Low Energy (BLE), for Windows, Android, iOS, Linux and macOS."
version: 0.0.21
repository: https://github.com/chan150/nrf_ble_dfu

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.7.0"

platforms:
  windows:
  android:
  ios:
  macos:
  linux:

topics:
  - nordic
  - nrf
  - ble
  - dfu

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: 
  flutter_blue_plus_winrt: 
  mobx: 
  permission_handler: 
  flutter_mobx: 
  file_picker: 
  archive: 
  path_provider: 
  path: 
  shared_preferences: 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 
  mobx_codegen: 
  build_runner: 
