name: nrf_ble_dfu
description: "Nordic DFU via ble"
version: 0.0.1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus_windows: ">=1.23.3"
  mobx: ">=2.3.3+2"
  permission_handler: ">=11.3.1"
  flutter_mobx: ">=2.2.1+1"
  file_picker: ">=8.0.2"
  archive: ">=3.4.10"
  path_provider: ">=2.1.3"
  path: ">=1.9.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ">=3.0.0"
  mobx_codegen: ">=2.6.1"
  build_runner: ">=2.4.9"
